### ISSUE TITLE
[bug] igb 5.17.4 does not compile with linux mainline 6.11-rc6

### ISSUE THREAD

**Issue by JonKohler** [intel/ethernet-linux-igb#3]
Hey all - thanks for the most recent 5.17.4 update, fixed up most things we were hitting in 6.11 mainline, except one lingering issue 

### Driver Tag/Commit

https://github.com/intel/ethernet-linux-igb/releases/tag/v5.17.4

### Custom Code

No

### OS Platform and Distribution

Linux 6.11-rc6 (431c1646e1f8) - https://github.com/torvalds/linux/tree/v6.11-rc6

### Bug description

Intel igb out of tree driver 5.17.4 does not compile with latest mainline, 6.11-rc6

Breakage appears to be from https://github.com/torvalds/linux/commit/2111375b85ad173d58e7b8604246a3de60950ac8 and series https://lore.kernel.org/all/20240709-feature_ptp_netnext-v17-0-b5317f50df2a@bootlin.com/

### Reproduction steps

```bash
1. Pull latest rc tag from Linux tree (https://github.com/torvalds/linux/tree/v6.11-rc6)
2. Try to compile with 5.17.4
3. Watch it go kaboom with error noted in logs below
```

### Expected Behavior

It compiles

### Actual Behavior

It does not compile

### Additional Data

```bash
Using mockbuild environment with el8 based userspace, and distro compiler (GCC 8.5 distro managed)
```

### Relevant log output

```shell
[igb] /builddir/build/BUILD/igb-5.17.4/src/igb_ethtool.c:3889:28: error: initialization of 'int (*)(struct net_device *, struct kernel_ethtool_ts_info *)' from incompatible pointer type 'int (*)(struct net_device *, struct ethtool_ts_info *)' [-Werror=incompatible-pointer-types]
[igb]   .get_ts_info            = igb_get_ts_info,
[igb]                             ^~~~~~~~~~~~~~~
[igb] /builddir/build/BUILD/igb-5.17.4/src/igb_ethtool.c:3889:28: note: (near initialization for 'igb_ethtool_ops.get_ts_info')
[igb] cc1: some warnings being treated as errors
```

**Comment by JonKohler** [comment]
cc @aloktion

**Comment by rwntr** [comment]
Having this issue as well.  Arch 6.11.6-arch1-1

**Comment by mniehren** [comment]
same issue on curren mainline kernel V6.12.2

**Comment by maaaat** [comment]
And the same issue with Alpine 3.21 that got released a few days ago with kernel 6.12.3.

**Comment by JonKohler** [comment]
Has since been fixed
